# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{foreign_model}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Nicholaides"]
  s.date = %q{2010-03-31}
  s.description = %q{Works for ActiveRecord and Mongoid}
  s.email = %q{mike@ablegray.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/foreign_model.rb",
     "spec/foreign_model_spec.rb"
  ]
  s.homepage = %q{http://github.com/nicholaides/foreign_model}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{ActiveRecord-like associations that work between models of different databases and database types.}
  s.test_files = [
    "spec/foreign_model_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<spec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<spec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<spec>, [">= 1.3.0"])
  end
end

